OPENAI_API_KEY = "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"

SUPABASE_URL = "https://ecnwdfhgrsgjvugtoamk.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbndkZmhncnNnanZ1Z3RvYW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTc0MzkyOTMsImV4cCI6MjAxMzAxNTI5M30.ZCLbmt1YNhUX8cU0WDurqyr6XGXRh6sPWwn4myXM-zM"

[connections.snowpark]
user = "SHAWNMAI"
password = "Nekgef-dijdum-3jekte"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "EWQBGGY-UK00228"
database = "BIGSUPPLYCO"
schema = "BIGSUPPLYCO"
